/**
 * OpenShorts Pro Studio V2 - Official Novel Character & Asset Presets
 * Pre-baked with visual DNA and matching portrait files from /character_images/
 */

import { CharacterDNA, WardrobePreset, LandmarkDNA } from '../types';

export const OFFICIAL_NOVEL_CHARACTERS: CharacterDNA[] = [
  {
    id: 'char_lee_heonsung',
    name: '이헌성',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 초반 남성 (대한민국 해군 소령 / 충무공 빙의 각성)',
    bodyBuild: '다부진 체격, 역삼각형 어깨, 182cm 탄탄한 군인 체형',
    faceFeatures: '날카로운 턱선, 짙은 눈썹, 흔들림 없는 형형한 눈빛, 압도적인 지휘관 아우라',
    hairStyle: '단정하고 짧은 깔끔한 투블럭 언더컷 흑발',
    fixedTraits: ['한국인', '해군 장교', '강렬한 눈빛', '절제된 유교적 품격', '카리스마'],
    avoidTraits: ['서양인', '장발', '장난스러운 표정', '과도한 3D'],
    refImagePath: '/character_images/이헌성.jpeg',
    lockedPromptBlock:
      '30s handsome sharp Korean naval officer, intense piercing unblinking eyes, commanding aura, muscular athletic physique, short clean undercut, stoic resolute jawline, high-contrast chiaroscuro lighting',
  },
  {
    id: 'char_yoo_chaewon',
    name: '유채원',
    sourceNovel: '불멸의 충무공',
    ageGender: '20대 후반 여성 (천재 해커 / AI 보안팀장 / 정실 약혼녀)',
    bodyBuild: '슬림하고 지적인 실루엣, 168cm 단아한 체형',
    faceFeatures: '투명하고 결점 없는 피부, 얇은 메탈 안경, 명민하고 결단력 있는 눈매',
    hairStyle: '세련되게 묶어 올린 검은색 포니테일',
    fixedTraits: ['한국인', '안경', '지적인 매력', 'AI 보안팀장', '냉철한 집중력'],
    avoidTraits: ['화려한 노출', '금발', '어색한 체형'],
    refImagePath: '/character_images/유채원.png',
    lockedPromptBlock:
      'late 20s beautiful Korean cyber security director, elegant glasses, slim sharp silhouette, sleek black hair ponytail, intelligent focused gaze, modern professional cybersecurity techwear',
  },
  {
    id: 'char_kim_kyunhee',
    name: '김견희 (대모)',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 중반 여성 (강남 지하 경제 지배자 / 거대 사채망 대모)',
    bodyBuild: '풍만하고 굴곡진 관능적 바디라인, 172cm 압도적 피지컬',
    faceFeatures: '고혹적이고 뇌쇄적인 눈빛, 붉은 립스틱, 여유롭고 치명적인 미소',
    hairStyle: '풍성한 웨이브 흑발 롱헤어',
    fixedTraits: ['한국인', '치명적 관능미', '고급 실크 드레스', '다크 느와르 아우라', '여왕'],
    avoidTraits: ['청순함', '수수한 옷차림', '소녀풍'],
    refImagePath: '/character_images/김견희.png',
    lockedPromptBlock:
      'mid 30s glamorous seductive Korean underground godmother, luxurious silk dress, heavy atmospheric tension, confident commanding smile, sensual aura, dark noir mood',
  },
  {
    id: 'char_choi_mihee',
    name: '최미희',
    sourceNovel: '불멸의 충무공',
    ageGender: '20대 초반 여성 (글로벌 K-팝 톱스타 루나이트 / 유채원 사촌)',
    bodyBuild: '날렵하고 유연한 아이돌 몸매, 166cm 황금비율',
    faceFeatures: '인형 같은 이목구비, 반짝이는 눈동자, 당돌하고 매혹적인 표정',
    hairStyle: '플래티넘 블론드 또는 세련된 탈색 투톤 레이어드컷',
    fixedTraits: ['한국인', 'K-팝 아이돌', '화려한 스타일', '당돌한 유혹', '스타성'],
    avoidTraits: ['수수한 정장', '중후함', '어두운 분위기'],
    refImagePath: '/character_images/최미희.png',
    lockedPromptBlock:
      'early 20s stunning K-pop top idol, platinum dyed hair, radiant charismatic stage beauty, energetic expressive eyes, modern trendy cropped fashion, flawless glowing skin',
  },
  {
    id: 'char_kim_taesam',
    name: '김태삼',
    sourceNovel: '불멸의 충무공',
    ageGender: '40대 남성 (전직 UDT 특수부대원 / 지상전 선봉장)',
    bodyBuild: '거대한 떡대, 흉터가 있는 구릿빛 피부, 185cm 95kg 근육질',
    faceFeatures: '굵은 선의 얼굴, 턱수염 자국, 충성스럽고 맹렬한 야수의 눈빛',
    hairStyle: '짧고 거친 군인 스포츠 헤어',
    fixedTraits: ['한국인', 'UDT 베테랑', '전술 장비', '강인함', '돌격대장'],
    avoidTraits: ['미소년', '유약함', '단정한 양복'],
    refImagePath: '/character_images/김태삼.png',
    lockedPromptBlock:
      '40s rugged battle-hardened Korean UDT veteran, scarred tanned skin, broad muscular shoulders, tactical gear, intimidating loyal gaze, tactical combat vest',
  },
  {
    id: 'char_park_sangwon',
    name: '박상원',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 초반 남성 (육군 소령 / 이헌성의 사관학교 동기)',
    bodyBuild: '정석적인 장교 체형, 180cm 단단한 군인 체구',
    faceFeatures: '선하고 곧은 눈매, 신뢰감을 주는 외모, 정직한 인상',
    hairStyle: '깔끔한 육군 표준 단발 스포츠',
    fixedTraits: ['한국인', '육군 소령', '정의감', '순정파', '전술 브레인'],
    avoidTraits: ['건달', '험상궂은 인상'],
    refImagePath: '/character_images/박상원.png',
    lockedPromptBlock:
      'early 30s sharp Korean Army Major, honorable expression, clean haircut, tactical service uniform, steadfast loyal gaze, military intelligence briefing room',
  },
  {
    id: 'char_oh_seongki',
    name: '오선기 (폭파)',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 남성 (UDT 폭파 전문가 / B급 콤비)',
    bodyBuild: '육중하고 탄탄한 근육질 체격, 전술 조끼 착용',
    faceFeatures: '익살스럽지만 전투 시 돌변하는 광기 어린 눈빛',
    hairStyle: '짧은 크루컷 헤어',
    fixedTraits: ['한국인', 'UDT 폭파병', 'C4 폭약 가방', '전술 고글', '인간병기'],
    avoidTraits: ['정장', '허약함'],
    refImagePath: '/character_images/오성기.png',
    lockedPromptBlock:
      '30s Korean heavy tactical demolition specialist, C4 rigging gear, tactical plate carrier, intense gritty battle demeanor, concrete dust and smoke',
  },
  {
    id: 'char_yuk_jaeji',
    name: '육재지 (저격)',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 남성 (UDT 초정밀 저격수 / B급 콤비)',
    bodyBuild: '날렵하고 긴 팔다리, 침착한 근육질',
    faceFeatures: '매서운 스나이퍼의 눈매, 한쪽 눈을 가늘게 뜨는 습관',
    hairStyle: '바람에 흩날리는 짧은 전술 헤어',
    fixedTraits: ['한국인', '저격수', '대구경 저격총', '길리 위장', '냉정한 살수'],
    avoidTraits: ['화려한 원색 옷', '살찐 체형'],
    refImagePath: '/character_images/육자지.png',
    lockedPromptBlock:
      '30s Korean master sniper, ghillie accents, holding heavy anti-materiel sniper rifle, razor-sharp focused eagle gaze, urban rooftop vantage point',
  },
  {
    id: 'char_cho_hana',
    name: '조하나',
    sourceNovel: '불멸의 충무공',
    ageGender: '20대 초반 여성 (걸그룹 멤버 / 박상원의 연인)',
    bodyBuild: '여리여리하고 슬림한 아이돌 체형, 164cm',
    faceFeatures: '사슴 같은 큰 눈망울, 보호본능을 자극하는 청순한 미모',
    hairStyle: '부드러운 다크브라운 웨이브 롱헤어',
    fixedTraits: ['한국인', '걸그룹 멤버', '청순가련', '보호본능', '순수함'],
    avoidTraits: ['근육질', '험악한 표정'],
    refImagePath: '/character_images/조하나.png',
    lockedPromptBlock:
      'early 20s delicate beautiful Korean girl group member, innocent teary eyes, soft brown long hair, casual oversized hoodie, fragile emotional expression',
  },
  {
    id: 'char_goo_yeonji',
    name: '구연지',
    sourceNovel: '불멸의 충무공',
    ageGender: '20대 후반 여성 (김견희 대모 직속 여성 경호원 / 무술 고수)',
    bodyBuild: '군살 없는 무술가 체형, 날렵한 근육',
    faceFeatures: '서늘하고 날카로운 눈매, 차가운 킬러의 인상',
    hairStyle: '깔끔하게 뒤로 넘긴 숏컷',
    fixedTraits: ['한국인', '여성 경호원', '블랙 수트', '택티컬 나이프', '무술 유단자'],
    avoidTraits: ['치마', '귀여운 표정'],
    refImagePath: '/character_images/구연지.jpeg',
    lockedPromptBlock:
      'late 20s sharp agile Korean female bodyguard, tailored black slim suit, holding tactical karambit knife, cold lethal gaze, rain-slicked dark alleyway',
  },
  {
    id: 'char_so_hyangsoon',
    name: '소향순',
    sourceNovel: '불멸의 충무공',
    ageGender: '20대 후반 여성 (김견희 대모 직속 여성 경호원 / 완력 고수)',
    bodyBuild: '탄탄한 피지컬, 어깨가 넓고 힘이 넘치는 여걸',
    faceFeatures: '당당하고 묵직한 카리스마, 굳게 다문 입술',
    hairStyle: '단정한 칼단발 흑발',
    fixedTraits: ['한국인', '여성 경호원', '블랙 수트', '쌍권총', '괴력'],
    avoidTraits: ['유약함', '화려한 드레스'],
    refImagePath: '/character_images/소향순.jpeg',
    lockedPromptBlock:
      'late 20s athletic intimidating Korean female enforcer, fitted tactical blazer, dual automatic pistols, unyielding fearless expression, high-contrast shadows',
  },
  {
    id: 'char_lin_jiahao',
    name: '린자하오 (대만)',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 남성 (대만 타이베이 지하 레지스탕스 리더)',
    bodyBuild: '민첩하고 마른 근육질, 스트리트 택티컬 웨어',
    faceFeatures: '반항적이고 영민한 눈빛, 날카로운 아시아계 외모',
    hairStyle: '자유분방한 텍스처 펌 흑발',
    fixedTraits: ['대만인', '레지스탕스', '사이버 펑크 감성', '타이베이 골목', '게릴라'],
    avoidTraits: ['군복 정복', '노인'],
    refImagePath: '/character_images/린자하오.png',
    lockedPromptBlock:
      '30s sharp Taiwanese underground resistance leader, street cyberpunk tactical jacket, neon-lit Taipei alley background, vigilant calculating gaze',
  },
  {
    id: 'char_sayama_ken',
    name: '사야마 켄 (일본)',
    sourceNovel: '불멸의 충무공',
    ageGender: '30대 중반 남성 (일본 해상자위대 정보장교 / 망명 조력자)',
    bodyBuild: '각 잡힌 장교 체형, 178cm 정갈한 제복 핏',
    faceFeatures: '고뇌하는 깊은 눈매, 지적이고 번민에 찬 엘리트 장교 인상',
    hairStyle: '단정하게 가르마를 탄 일본식 클래식 헤어',
    fixedTraits: ['일본인', '자위대 제복', '비밀 첩보 파일', '고뇌하는 영혼'],
    avoidTraits: ['극우 군국주의 표정', '캐주얼 의류'],
    refImagePath: '/character_images/사야마켄.png',
    lockedPromptBlock:
      'mid 30s distinguished Japanese JMSDF intelligence officer, dark naval dress uniform, carrying classified blueprint folder, conflicted brooding gaze, Yokohama port harbor at dusk',
  },
  {
    id: 'char_tariq',
    name: '타리크 알 아흐메드 (중동)',
    sourceNovel: '불멸의 충무공',
    ageGender: '40대 남성 (중동 에너지 재벌 총수 / 그림자 스폰서)',
    bodyBuild: '당당하고 웅장한 체구, 188cm 거구',
    faceFeatures: '풍성하게 다듬은 턱수염, 강인한 아랍계 귀족의 눈빛',
    hairStyle: '고급 터번 또는 깔끔한 정장 헤어',
    fixedTraits: ['중동계', '에너지 재벌', '초호화 명품 슈트', '묵직한 은혜 갚기'],
    avoidTraits: ['남루한 옷', '테러리스트 복장'],
    refImagePath: '/character_images/타리크 알 아흐메드.png',
    lockedPromptBlock:
      '40s majestic Middle Eastern billionaire tycoon, bespoke tailored charcoal suit, luxurious gold watch, deeply grateful and commanding demeanor, luxury executive suite overlooking Dubai skyline',
  },
  {
    id: 'char_chen_jianguo',
    name: '천지엔궈 (중국 흑막)',
    sourceNovel: '불멸의 충무공',
    ageGender: '50대 남성 (중국 국가안전부 MSS 제1국장 / 홍염 작전 총책)',
    bodyBuild: '두툼한 중년 체구, 느긋하지만 서늘한 자세',
    faceFeatures: '냉혹하고 감정을 읽을 수 없는 뱀 같은 눈매, 굳은 표정',
    hairStyle: '올백으로 넘긴 희끗희끗한 흑발',
    fixedTraits: ['중국인', 'MSS 흑막', '고위 관료 인민복 또는 블랙 슈트', '절대악'],
    avoidTraits: ['선한 웃음', '허약함'],
    refImagePath: '/character_images/천지엔궈.png',
    lockedPromptBlock:
      '50s ruthless Chinese MSS intelligence chief, sharp dark Mao-style executive suit, cold reptilian calculated glare, heavy shadows, Beijing grand state room',
  },
  {
    id: 'char_jo_gihak',
    name: '조기학 (국내 매국 실세)',
    sourceNovel: '불멸의 충무공',
    ageGender: '60대 남성 (여당 막후 실세 / 탄핵 및 부정선거 주도)',
    bodyBuild: '배가 약간 나온 탐욕스러운 정치인 체형',
    faceFeatures: '탐욕과 오만함이 가득 찬 눈빛, 기름진 피부, 교활한 입꼬리',
    hairStyle: '2대8 정통 정치인 가르마 흑발',
    fixedTraits: ['한국인', '부패 정치인', '고급 맞춤 양복', '금배지', '매국노'],
    avoidTraits: ['청렴함', '젊은 외모'],
    refImagePath: '/character_images/조기학.png',
    lockedPromptBlock:
      '60s corrupt Korean political kingmaker, tailored navy suit with gold national assembly pin, greedy sneering expression, luxurious VIP club lounge, cigarette smoke',
  },
  {
    id: 'char_takahashi_ryuzo',
    name: '타카하시 류조 (일본 막료장)',
    sourceNovel: '불멸의 충무공',
    ageGender: '50대 후반 남성 (일본 해상자위대 막료장 / 7광구 봉쇄 총지휘)',
    bodyBuild: '뻣뻣하고 각 잡힌 군국주의 지휘관 체형',
    faceFeatures: '오만하고 경멸 어린 눈매, 굳게 다문 입술',
    hairStyle: '백발이 섞인 짧은 군인 스포츠',
    fixedTraits: ['일본인', '자위대 제복', '극우 군국주의', '이지스 함대 지휘관'],
    avoidTraits: ['온화함', '캐주얼'],
    refImagePath: '/character_images/타카하시 류조.png',
    lockedPromptBlock:
      'late 50s arrogant Japanese admiral, JMSDF high-ranking naval white uniform, stern imperialistic expression, commanding combat bridge of modern Aegis destroyer',
  },
  {
    id: 'char_song_gunho',
    name: '송건호 (배신자 장군)',
    sourceNovel: '불멸의 충무공',
    ageGender: '50대 남성 (육군 3성 중장 / 안창호함 사건 조작 주범)',
    bodyBuild: '장성급 장교 체형, 굵은 목덜미',
    faceFeatures: '욕망과 배신의 독기가 서린 눈빛, 각진 턱',
    hairStyle: '단정한 3성 장군 군인 머리',
    fixedTraits: ['한국인', '3성 장군', '육군 정복', '계급장', '군 내부 반역자'],
    avoidTraits: ['순수한 군인', '청년'],
    refImagePath: '/character_images/송건호.png',
    lockedPromptBlock:
      '50s corrupt Korean 3-star lieutenant general, formal army service dress with 3 silver stars, deceitful power-hungry gaze, grand defense ministry headquarters',
  },
];

export const OFFICIAL_NOVEL_WARDROBES: WardrobePreset[] = [
  {
    id: 'wb_lee_naval_duty',
    characterId: 'char_lee_heonsung',
    name: '해군 근무복 (함상복)',
    outfitDescription: '짙은 네이비 해군 디지털 위장 함상 근무복, 소령 계급장, 벨크로 명찰',
    shoesProps: '전술 함상화, 기계식 방수 다이버 시계',
    condition: '단정함',
    refImagePath: '/character_images/Man_in_navy_202603311246.jpeg',
  },
  {
    id: 'wb_lee_tactical_black',
    characterId: 'char_lee_heonsung',
    name: '특수작전 블랙 택티컬',
    outfitDescription: '블랙 전술 방탄 조끼, MP7 탄창 파우치, 전술 카고 팬츠',
    shoesProps: '전술 부츠, MP7 소음기 장착 기관단총',
    condition: '작전 중',
    refImagePath: '/character_images/Man_in_tactical_202603311246.jpeg',
  },
  {
    id: 'wb_yoo_office',
    characterId: 'char_yoo_chaewon',
    name: '보안팀장 오피스 룩',
    outfitDescription: '다크 차콜 슬림 블레이저, 실크 화이트 셔츠, 슬랙스',
    shoesProps: '블랙 스틸레토 힐, 암호화 스마트패드',
    condition: '단정함',
    refImagePath: '/character_images/Girl_standing_in_202603311246.jpeg',
  },
  {
    id: 'wb_kim_silk_dress',
    characterId: 'char_kim_kyunhee',
    name: '대모의 블랙 실크 이브닝 드레스',
    outfitDescription: '어깨 라인이 드러나는 최고급 블랙 실크 슬릿 드레스, 다이아몬드 목걸이',
    shoesProps: '하이힐, 장총 케이스',
    condition: '화려함',
    refImagePath: '/character_images/VVIP_underground_club_202603311246.jpeg',
  },
];

export const OFFICIAL_NOVEL_LANDMARKS: LandmarkDNA[] = [
  {
    id: 'lm_gangnam_vvip_club',
    name: '강남 VVIP 지하 밀실 (아스포델)',
    location: '서울 강남구 지하 3층',
    structureMaterials: '어두운 대리석 바닥, 방음 가죽 패널, 앤틱 마호가니 원목 책상',
    lifeTraces: '크리스탈 위스키 잔, 묵직한 서류철, 모니터 월',
    lightingAura: '무거운 키아로스쿠로 무드 조명, 깊은 그림자',
    refImagePaths: ['/character_images/VVIP_underground_club_202603311246.jpeg'],
    lockedPromptBlock:
      'dark luxurious underground executive office, antique mahogany desk, heavy atmospheric chiaroscuro lighting, crystal whiskey glasses, high-end VIP ambiance',
  },
  {
    id: 'lm_national_assembly',
    name: '국회의사당 본회의장 및 의원실',
    location: '서울 영등포구 여의도동',
    structureMaterials: '대형 화강암 기둥, 국회 엠블럼 원목 단상, 정갈한 회의 테이블',
    lifeTraces: '법안 서류, 속기록, 국회 출입증',
    lightingAura: '격조 높은 실내 조명, 권력의 엄숙한 공기',
    refImagePaths: [],
    lockedPromptBlock:
      'grand Korean national assembly hall, polished granite columns, formal parliament wooden dais, dramatic ceiling lights, solemn political tension',
  },
  {
    id: 'lm_shadow_dock',
    name: '그림자 함대 군산 비밀 건조 독 (Dock)',
    location: '전북 군산 폐조선소 지하 비밀 도크',
    structureMaterials: '거대한 녹슨 강철 크레인, 군함 개조용 비계, 철골 트러스 구조',
    lifeTraces: '용접 불꽃, 천궁 미사일 캐니스터, 빗물 고인 콘크리트 바닥',
    lightingAura: '어두운 밤바다 배경, 푸른 용접 불꽃과 주황색 작업등',
    refImagePaths: [],
    lockedPromptBlock:
      'secret underground naval shipyard dry dock, massive warship under modification, welding sparks scattering in dark, industrial steel cranes, moody atmospheric reflections',
  },
];
